# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'zcPhoneValidation' do
  # Pods for zcPhoneValidation

  pod 'AccountKit'

  target 'zcPhoneValidationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
